### ISSUE TITLE
Render fails if the Scene is named anything else then "Scene"

### ISSUE THREAD

**Issue by de-illest** [EternalTrail/eeVR#12]
error log:
```
Traceback (most recent call last):
  File "C:\Users\ilia\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\VRRenderer.py", line 650, in execute
    renderer.render_and_save() 
  File "C:\Users\ilia\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\VRRenderer.py", line 588, in render_and_save
    imageList, imageList2 = self.render_images()
  File "C:\Users\ilia\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\VRRenderer.py", line 566, in render_images
    img1, img2 = self.render_image(direction)
  File "C:\Users\ilia\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\VRRenderer.py", line 472, in render_image
    tmp = bpy.data.scenes['Scene'].render.filepath
KeyError: 'bpy_prop_collection[key]: key "Scene" not found'

location: <unknown location>:-1
```

**Comment by EternalTrail** [comment]
Thanks for letting me know of this issue, as of 75d5991 this issue has been fixed!
