### ISSUE TITLE
what ever type of your render i render it fails in one big file 

### ISSUE THREAD

**Issue by dominikkinimod** [EternalTrail/eeVR#32]
Python: Traceback (most recent call last):
  File "C:\Users\kinimod\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\eeVR-master\VRRenderer.py", line 711, in execute
    renderer.render_and_save() 
  File "C:\Users\kinimod\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\eeVR-master\VRRenderer.py", line 638, in render_and_save
    imageList, imageList2 = self.render_images()
  File "C:\Users\kinimod\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\eeVR-master\VRRenderer.py", line 616, in render_images
    img1, img2 = self.render_image(direction)
  File "C:\Users\kinimod\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\eeVR-master\VRRenderer.py", line 588, in render_image
    bpy.ops.render.render(write_still=True)
  File "C:\Program Files\Blender Foundation\Blender 3.00\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot write a single file with an animation format selected

location: <unknown location>:-1

**Comment by EternalTrail** [comment]
We are talking about different things. I am talking about the issue that is opened up here. I am currently working on implementing a script version of your clean corner solution, but this is not why this issue was opened up, as shown by the title of this thread as well as the error message that you pasted here. Feel free to open up a separate issue relating to the corner issue, as that way it'll be easier to keep track of it.

**Comment by EternalTrail** [comment]
No problem. I will contact you in the near future about your solution. I currently have a script that creates a six (or twelve for stereo) camera setup as you have done in your blend file. Hopefully it will not be too tedious to implement the clean corner rendering.

**Comment by dominikkinimod** [comment]
Oh that will be awesome...
Good luck with that. I never programmed anything in python or in which
language addons are written. I can imagine it is tricky... so GL and have
fun XD

pá 15. 10. 2021 v 20:13 odesílatel Andrius ***@***.***>
napsal:
