### ISSUE TITLE
Update maybe for Blender 3.0+?

### ISSUE THREAD

**Issue by bobble009** [EternalTrail/eeVR#43]
Current error log on a fresh Blender 3.2.1 file with Stereo3D enabled, png file is set, panoramic 90degree camera. I used to be able to render in 3.0, but it went back to giving me the same error. Even on a new Windows OS install after formatting drive.

Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\eeVR-master\VRRenderer.py", line 703, in execute
    renderer.render_and_save() 
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\eeVR-master\VRRenderer.py", line 636, in render_and_save
    imageList, imageList2 = self.render_images()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\eeVR-master\VRRenderer.py", line 613, in render_images
    self.set_camera_direction(direction)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\eeVR-master\VRRenderer.py", line 480, in set_camera_direction
    self.scene.render.resolution_x = self.camera_shift[direction][2]
TypeError: bpy_struct: item.attr = val: RenderSettings.resolution_x expected an int type, not float

**Comment by nagadomi** [comment]
it is already fixed in https://github.com/EternalTrail/eeVR/pull/38
