### ISSUE TITLE
Does not render anything on 3.5 / 3.4

### ISSUE THREAD

**Issue by Waldgeister** [EternalTrail/eeVR#48]
Unfortunately the plugin seems not to work on Blender 3.5 and also 3.4. Or is due to the Apple Silicon Architecture? The scene is nothing special just the blank default one.

`bpy.ops.object.camera_add(enter_editmode=False, align='VIEW', location=(0, 0, 0), rotation=(1.47306, -2.7808e-08, -1.41023), scale=(1, 1, 1))

Python: Traceback (most recent call last):
    File "/Users/xxx/Library/Application Support/Blender/3.5/scripts/addons/eeVR-master/__init__.py", line 55, in execute
    renderer = Renderer(context, False)
    File "/Users/xxx/Library/Application Support/Blender/3.5/scripts/addons/eeVR-master/renderer.py", line 371, in __init__
    self.shader = gpu.types.GPUShader(vertex_shader, frag_shader)

Exception: Shader Compile Error, see console for more details`

**Comment by ecations** [comment]
For me EeVR doesn't even show up in the latest Blender (3.5.0).
It used to require going to the "testing" category in the addons manager, but now there is no longer such a tab..

**Comment by nagadomi** [comment]
@ecations I have posted a fix for that issue in #49, works with only one line change.
@Waldgeister With the above changes, it worked on Blender 3.5 + Linux, so I think the problem is due to macOS. 
might be related to https://blender.stackexchange.com/questions/286919/addon-stopped-working-on-mac-metal-in-v3-5-due-to-shader-compile-error-console

**Comment by Waldgeister** [comment]
@nagadomi Yes I found that one too and checked the source of renderer.py. But it does not use any of the listed glEnable, glDisable or ShaderCreateInfo commands.

**Comment by nagadomi** [comment]
Maybe the shader code should be compiled using new `gpu.shader.create_from_info()` instead of `gpu.types.GPUShader()`.
https://github.com/EternalTrail/eeVR/blob/86048cd3e24ed25e43f62cfd125f88ad0a71e7d9/renderer.py#L371

I don't have a mac machine so I am not sure that is the cause.

**Comment by Waldgeister** [comment]
I would love to fix it. But I'm only used to develop in Swift. So the stackexchange example is quite cryptic to me. Testing shouldn't be a problem.

**Comment by nagadomi** [comment]
I've tried updating renderer.py to use the new gpu module. Not tested in detail. (many of the texture parameters has been lost, so there may be differences from previous versions)
https://github.com/nagadomi/eeVR/commit/4781816c95d6c5f549e5cba916437e40aa823c49

Note that this commit does not include the changes in #49.

**Comment by Sasatari** [comment]
Two things about Mac (M1 in use here):
- Whatever I download here, it still needs a manual change to run with the latest Blender version, like stated above. Unzip eeVR, make the change (replace "testing" with "community" and zip it again. So it´ll show up.
- The render error @Waldgeister reported can be solved by going to the preferences and set the GPU BackEnd to "OpenGL". By default it´s "Metal", but that doesn´t work for me.

**Comment by Waldgeister** [comment]
@Sasatari Just tested the openGL workaround: The rendered output is indeed completely black. But even more, all the objects, camera, etc turn also black in the 3D viewport. I had to change the view port shading several times and back again to get regular coloring. 
![Screenshot allblack](https://user-images.githubusercontent.com/5500230/235253867-2721355c-45ad-498a-a6ff-4c83f5cf2db6.jpg)

**Comment by Sasatari** [comment]
> @Sasatari Just tested the openGL workaround: The rendered output is indeed completely black. But even more, all the objects, camera, etc turn also black in the 3D viewport. I had to change the view port shading several times and back again to get regular coloring.

Yes, same here, but I´m not deep enough into Blender (My main software still is Lightwave 3D) to figure out, why this happens. And actually have a severe lack of time. Will try to find some Blender on Mac users who can help with that.

**Comment by Sasatari** [comment]
Just did a View Render (F11) and there I got the expected result. So it seems to work in general, must be a simple setting somewhere I guess.

<img width="434" alt="RenderView" src="https://user-images.githubusercontent.com/17954889/237061081-3425b193-dd38-4af9-b907-4225adc04141.png">

**Comment by Waldgeister** [comment]
I guess this is only one of the segments you are seeing in the viewer. Did you activate the "keep temporary work files" in options? 

This is how it looks for me. Both in Metal and OpenGL with the new b35 version of @nagadomi 
<img width="809" alt="Black result 2023-05-12 um 21 25 13" src="https://github.com/EternalTrail/eeVR/assets/5500230/019fba12-1184-4c76-bee3-421bd0909316">

**Comment by Sasatari** [comment]
Didn´t check temp, now I did and this is what I get:

<img width="867" alt="keepTemp" src="https://github.com/EternalTrail/eeVR/assets/17954889/abf75675-d353-4527-af12-fac84e24368d">

What do you mean with b35-version? I have no idea what you´re talking about. Checked his Git, but don´t see a clue.

**Comment by Sasatari** [comment]
Thank you so much! This works fine on my 2020 13 inch M1 MBP with Blender 3.5

**Comment by SAM-tak** [comment]
Already fixed in #51
