### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by S00pergang** [EternalTrail/eeVR#55]
I get an error when trying to use this and render in Blender 4.0

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\eeVR\__init__.py", line 57, in execute
    renderer.render_and_save()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\eeVR\renderer.py", line 719, in render_and_save
    imageList, imageList2 = self.render_images()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\eeVR\renderer.py", line 707, in render_images
    imgl, imgr = self.render_image(direction)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\eeVR\renderer.py", line 674, in render_image
    bpy.ops.render.render(write_still=True)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Cannot write a single file with an animation format selected
```

What am I doing wrong!?

**Comment by SAM-tak** [comment]
Fixed in #57
