### ISSUE TITLE
Cannot Save

### ISSUE THREAD

**Issue by KC098** [EternalTrail/eeVR#61]
Whenever I'm trying to render I get a permission denied error.

Python: Traceback (most recent call last):
  ```
File "C:\Users\suzanne\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\eeVR-master\__init__.py", line 60, in execute
    renderer.render_and_save()
  File "C:\Users\suzanne\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\eeVR-master\renderer.py", line 748, in render_and_save
    imageList, imageList2 = self.render_images()
  File "C:\Users\suzanne\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\eeVR-master\renderer.py", line 736, in render_images
    imgl, imgr = self.render_image(direction)
  File "C:\Users\suzanne\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\eeVR-master\renderer.py", line 676, in render_image
    bpy.ops.render.render(write_still=True)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Render error (Permission denied) cannot save: 'C:\temp_img_store_20508_back.tga'
```
Any solutions?

**System information (please complete the following information):**
 - OS: Windows 11
 - Processor: AMD Ryzen 9 6800HS
 - Graphics card: AMD Radeon RX 6700S
 - Graphics driver: 23.12.1
 - Blender version: 4.0.2

**Comment by SAM-tak** [comment]
same issue?
https://github.com/EternalTrail/eeVR/issues/58

**Comment by nagadomi** [comment]
@SAM-tak 
I checked the preferences on Windows with `--factory-startup`, `preferences.filepaths.temporary_directory` was empty.
From the documentation, Blender uses `TEMP` environment variable if `preferences.filepaths.temporary_directory` is not specified.
https://docs.blender.org/manual/ja/3.6/advanced/blender_directory_layout.html#temporary-directory

So if temporary_directory is not specified, it is safe to use platform temporary directory.
```python
if context.preferences.filepaths.temporary_directory:
    tmpdir = bpy.path.abspath(context.preferences.filepaths.temporary_directory)
else:
    # import tempfile
    tmpdir = tempfile.gettempdir()
 ```

**Comment by SAM-tak** [comment]
fixed
https://github.com/EternalTrail/eeVR/commit/eb832f58845bab75f09d07fe362558abd170197f
